# Generated by Django 4.1.3 on 2022-11-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(verbose_name=11)),
                ('nombre_usuario', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.TextField(verbose_name=11)),
                ('username', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('tipo_nivel', models.TextField()),
                ('estatus', models.TextField()),
                ('registrado_por', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
